name: Storybook Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16 # Use Node.js 16

      - name: Install Yarn
        run: npm install -g yarn@latest

      - name: Install dependencies
        run: yarn

      - name: Build Storybook
        run: yarn build-storybook && yarn deploy-storybook

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.STORYBOOK_ID }}
          publish_branch: gh-pages
          publish_dir: storybook-static # or the directory where your Storybook build is generated

