# .github/workflows/chromatic.yml

# Workflow name
name: 'StoryBook'

# Event for the workflow
on: push

# List of jobs
jobs:
  test:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v3
      - run: yarn
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
